### ISSUE TITLE
无法编译通过

### ISSUE THREAD

**Issue by kingvision** [HRLTY/DenseFace3D#1]
你好，
      我用Linux系统编译您的代码出错，对于auto等表示符不识别。
请问，怎么解决？
谢谢

**Comment by HRLTY** [comment]
Please make sure to use C++ 11. (already specified in CMakeList.txt).

**Comment by kingvision** [comment]
i used the C++ 11, but i still got the error

**Comment by HRLTY** [comment]
Does your compiler fully supports C11? What's the specific error message?

Rui Huang

**Comment by kingvision** [comment]
The error is:
DenseFace3D.cpp:235:19: error: ‘i’ does not name a type
         for (auto i = triangleList.begin(); i != triangleList.end();i++){

**Comment by HRLTY** [comment]
It looks like a lack of C11 support for the auto type deduction. Are you using cmake to generate the building script? make sure your version of cmake supports the C11 direction(set (CMAKE_CXX_STANDARD 11)), or you can add compiler flag for C11 yourself. You could try to compile a demo C11 source file to check this. Hope it helps. :D
