### ISSUE TITLE
doesn't build?

### ISSUE THREAD

**Issue by atv2016** [HRLTY/DenseFace3D#2]
-- Boost version: 1.60.0
CMake Error at CMakeLists.txt:35 (include):
  include could not find load file:

    ../dlib-19.0/dlib/cmake

-- Configuring incomplete, errors occurred!
See also "/Users/bla/Downloads/DenseFace3D-master/build/CMakeFiles/CMakeOutput.log".
Daedalus:build bla $ ls -l ../dlib-19.0/dlib/cmake
-rw-r--r--  1 bla staff  3991 25 Jun  2016 ../dlib-19.0/dlib/cmake

**Comment by atv2016** [comment]
Ok i got this to build by changing your CMakeLists.txt file

**Comment by HRLTY** [comment]
Please define corresponding dlib root macro.
